all_03: day-03/solution-p1 day-03/solution-p2

day-03/solution-p1: day-03/p1.o
	$(CC) $(CFLAGS) $< -o $@ $(LDFLAGS)

day-03/solution-p2: day-03/p2.o
	$(CC) $(CFLAGS) $< -o $@ $(LDFLAGS)

.PHONY: all_03
